# Generated by Django 3.1.7 on 2021-07-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_answers_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='structured',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000, null=True)),
                ('answers', models.CharField(max_length=100000, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='answers',
            name='B',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='C',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='answers',
            name='D',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='A',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
